// Demo data for PlanPulse platform
// This allows users to explore the platform without signing up

export const DEMO_ORGANIZATION = {
  id: 'demo-org-id',
  name: 'City of Sacramento',
  type: 'city',
  slug: 'city-of-sacramento',
};

export const DEMO_USER = {
  id: 'demo-user-id',
  email: 'demo@planpulse.io',
  full_name: 'Demo Planner',
  role: 'admin',
  organization_id: DEMO_ORGANIZATION.id,
};

export const DEMO_PROJECTS = [
  {
    id: 'proj-1',
    name: 'Downtown Complete Streets Plan',
    type: 'complete_streets',
    discipline: 'transportation',
    status: 'active',
    description: 'Comprehensive redesign of downtown corridors to improve safety and accessibility for all users.',
    client_name: 'City of Sacramento',
    budget: 2500000,
    spent: 875000,
    start_date: '2024-03-01',
    end_date: '2025-06-30',
    center_lat: 38.5816,
    center_lng: -121.4944,
    caltrans_project_number: 'STPL-5002(123)',
    federal_aid_number: '03-SAC-001',
    funding_source: 'ATP Cycle 6',
    updated_at: '2024-11-20T10:30:00Z',
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'proj-2',
    name: 'American River Trail Extension',
    type: 'trail_plan',
    discipline: 'transportation',
    status: 'planning',
    description: 'Extend the American River Parkway trail system to connect underserved neighborhoods.',
    client_name: 'Sacramento County',
    budget: 4200000,
    spent: 125000,
    start_date: '2024-09-01',
    end_date: '2026-12-31',
    center_lat: 38.6047,
    center_lng: -121.3758,
    caltrans_project_number: 'ATPL-5002(456)',
    funding_source: 'ATP Cycle 7',
    updated_at: '2024-11-18T14:20:00Z',
    created_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'proj-3',
    name: 'Safe Routes to School - Oak Park',
    type: 'atp',
    discipline: 'transportation',
    status: 'active',
    description: 'Improve pedestrian and bicycle infrastructure around Oak Park elementary schools.',
    client_name: 'Sacramento City USD',
    budget: 850000,
    spent: 420000,
    start_date: '2024-01-15',
    end_date: '2024-12-31',
    center_lat: 38.5483,
    center_lng: -121.4559,
    caltrans_project_number: 'ATPL-5002(789)',
    federal_aid_number: '03-SAC-002',
    funding_source: 'ATP Cycle 5',
    updated_at: '2024-11-22T09:15:00Z',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'proj-4',
    name: 'Regional Transit Priority Corridors',
    type: 'transit_plan',
    discipline: 'regional',
    status: 'active',
    description: 'Identify and implement transit priority treatments on key corridors.',
    client_name: 'SacRT',
    budget: 1800000,
    spent: 650000,
    start_date: '2024-04-01',
    end_date: '2025-03-31',
    center_lat: 38.5676,
    center_lng: -121.4684,
    funding_source: 'CMAQ',
    updated_at: '2024-11-21T16:45:00Z',
    created_at: '2024-04-01T00:00:00Z',
  },
  {
    id: 'proj-5',
    name: 'Local Road Safety Plan',
    type: 'safety_plan',
    discipline: 'transportation',
    status: 'planning',
    description: 'Develop a comprehensive safety action plan targeting high-injury network locations.',
    client_name: 'City of Sacramento',
    budget: 450000,
    spent: 45000,
    start_date: '2024-10-01',
    end_date: '2025-09-30',
    center_lat: 38.5816,
    center_lng: -121.4944,
    funding_source: 'SS4A Planning',
    updated_at: '2024-11-15T11:00:00Z',
    created_at: '2024-10-01T00:00:00Z',
  },
  {
    id: 'proj-6',
    name: 'Midtown Specific Plan Update',
    type: 'specific_plan',
    discipline: 'urban',
    status: 'active',
    description: 'Update the Midtown Specific Plan to accommodate increased housing density and mixed-use development.',
    client_name: 'City of Sacramento',
    budget: 380000,
    spent: 95000,
    start_date: '2024-06-01',
    end_date: '2025-12-31',
    center_lat: 38.5720,
    center_lng: -121.4789,
    funding_source: 'SB 2 Planning Grant',
    updated_at: '2024-11-19T13:30:00Z',
    created_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'proj-7',
    name: 'Elk Grove Main Street Revitalization',
    type: 'main_street',
    discipline: 'rural',
    status: 'planning',
    description: 'Downtown revitalization plan focusing on walkability, local business support, and placemaking.',
    client_name: 'City of Elk Grove',
    budget: 275000,
    spent: 28000,
    start_date: '2024-11-01',
    end_date: '2025-08-31',
    center_lat: 38.4088,
    center_lng: -121.3716,
    funding_source: 'REAP 2.0',
    updated_at: '2024-11-20T10:00:00Z',
    created_at: '2024-11-01T00:00:00Z',
  },
];

export const DEMO_GRANT_APPLICATIONS = [
  {
    id: 'grant-1',
    name: 'ATP Cycle 7 - Downtown Bike Network',
    description: 'Protected bike lane network connecting downtown to midtown neighborhoods.',
    amount_requested: 5200000,
    match_amount: 680000,
    match_source: 'Measure A Funds',
    status: 'submitted',
    deadline: '2025-01-15',
    submitted_at: '2024-11-01T00:00:00Z',
    grant_program: 'Active Transportation Program (ATP)',
    project_id: 'proj-1',
  },
  {
    id: 'grant-2',
    name: 'HSIP - High Injury Intersections',
    description: 'Signal improvements and pedestrian safety enhancements at 12 high-crash locations.',
    amount_requested: 2800000,
    match_amount: 311000,
    match_source: 'General Fund',
    status: 'drafting',
    deadline: '2025-02-28',
    grant_program: 'Highway Safety Improvement Program (HSIP)',
    project_id: 'proj-5',
  },
  {
    id: 'grant-3',
    name: 'SS4A Planning Grant',
    description: 'Develop a comprehensive Safety Action Plan for the City.',
    amount_requested: 400000,
    match_amount: 100000,
    match_source: 'In-kind staff time',
    status: 'awarded',
    deadline: '2024-08-15',
    submitted_at: '2024-07-20T00:00:00Z',
    decision_date: '2024-10-01',
    amount_awarded: 400000,
    grant_program: 'Safe Streets and Roads for All (SS4A)',
    project_id: 'proj-5',
  },
  {
    id: 'grant-4',
    name: 'TDA Article 3 - Trail Wayfinding',
    description: 'Install wayfinding signage along American River Trail extension.',
    amount_requested: 125000,
    match_amount: 0,
    status: 'under_review',
    deadline: '2024-09-30',
    submitted_at: '2024-09-15T00:00:00Z',
    grant_program: 'Transportation Development Act (TDA) Article 3',
    project_id: 'proj-2',
  },
];

export const DEMO_ENGAGEMENT_PROJECTS = [
  {
    id: 'eng-1',
    name: 'Downtown Complete Streets Input Map',
    description: 'Share your ideas for improving walking, biking, and transit downtown.',
    status: 'active',
    start_date: '2024-10-01',
    end_date: '2024-12-31',
    center_lat: 38.5816,
    center_lng: -121.4944,
    zoom_level: 14,
    project_id: 'proj-1',
    input_count: 247,
  },
  {
    id: 'eng-2',
    name: 'Oak Park SRTS Community Input',
    description: 'Help us identify safety concerns around Oak Park schools.',
    status: 'active',
    start_date: '2024-09-15',
    end_date: '2024-11-30',
    center_lat: 38.5483,
    center_lng: -121.4559,
    zoom_level: 15,
    project_id: 'proj-3',
    input_count: 89,
  },
  {
    id: 'eng-3',
    name: 'Trail Extension Route Preferences',
    description: 'Vote on preferred alignment options for the trail extension.',
    status: 'draft',
    start_date: '2025-01-15',
    end_date: '2025-03-15',
    center_lat: 38.6047,
    center_lng: -121.3758,
    zoom_level: 13,
    project_id: 'proj-2',
    input_count: 0,
  },
];

export const DEMO_COMMUNITY_INPUTS = [
  {
    id: 'input-1',
    engagement_id: 'eng-1',
    input_type: 'pin',
    category: 'safety',
    title: 'Dangerous intersection',
    content: 'Cars frequently run the red light here. Need better signal timing and enforcement.',
    sentiment: 'negative',
    upvotes: 34,
    lat: 38.5795,
    lng: -121.4932,
    created_at: '2024-11-15T14:30:00Z',
  },
  {
    id: 'input-2',
    engagement_id: 'eng-1',
    input_type: 'pin',
    category: 'infrastructure',
    title: 'Need bike parking',
    content: 'There is nowhere to lock bikes near the farmers market. Would use bike more if parking available.',
    sentiment: 'suggestion',
    upvotes: 28,
    lat: 38.5823,
    lng: -121.4956,
    created_at: '2024-11-14T10:15:00Z',
  },
  {
    id: 'input-3',
    engagement_id: 'eng-1',
    input_type: 'pin',
    category: 'accessibility',
    title: 'ADA ramp needed',
    content: 'Missing curb ramp on northwest corner. My wheelchair cannot cross here safely.',
    sentiment: 'negative',
    upvotes: 42,
    lat: 38.5801,
    lng: -121.4918,
    created_at: '2024-11-12T16:45:00Z',
  },
  {
    id: 'input-4',
    engagement_id: 'eng-2',
    input_type: 'pin',
    category: 'safety',
    title: 'No crosswalk for students',
    content: 'Kids have to cross 4 lanes with no marked crosswalk to get to school.',
    sentiment: 'negative',
    upvotes: 56,
    lat: 38.5489,
    lng: -121.4571,
    created_at: '2024-10-20T08:30:00Z',
  },
  {
    id: 'input-5',
    engagement_id: 'eng-1',
    input_type: 'pin',
    category: 'other',
    title: 'Love the new bike lane!',
    content: 'The protected bike lane on J Street is amazing. Please extend it further east!',
    sentiment: 'positive',
    upvotes: 67,
    lat: 38.5812,
    lng: -121.4889,
    created_at: '2024-11-10T12:00:00Z',
  },
];

export const DEMO_TRANSIT_METRICS = [
  { route_id: '1', route_name: 'Route 1 - Greenback', ridership: 4520, revenue_hours: 156, cost_per_passenger: 4.82, on_time_performance: 0.87 },
  { route_id: '2', route_name: 'Route 2 - Riverside', ridership: 3890, revenue_hours: 142, cost_per_passenger: 5.21, on_time_performance: 0.91 },
  { route_id: '15', route_name: 'Route 15 - Del Paso', ridership: 2150, revenue_hours: 98, cost_per_passenger: 6.45, on_time_performance: 0.84 },
  { route_id: '23', route_name: 'Route 23 - El Camino', ridership: 1780, revenue_hours: 88, cost_per_passenger: 7.12, on_time_performance: 0.79 },
  { route_id: '30', route_name: 'Route 30 - J Street', ridership: 5210, revenue_hours: 168, cost_per_passenger: 4.15, on_time_performance: 0.93 },
  { route_id: '51', route_name: 'Route 51 - Broadway', ridership: 3420, revenue_hours: 124, cost_per_passenger: 5.67, on_time_performance: 0.86 },
  { route_id: '62', route_name: 'Route 62 - Freeport', ridership: 1950, revenue_hours: 92, cost_per_passenger: 6.89, on_time_performance: 0.82 },
  { route_id: '81', route_name: 'Route 81 - Florin', ridership: 2680, revenue_hours: 108, cost_per_passenger: 5.98, on_time_performance: 0.88 },
];

export const DEMO_CRASH_DATA = [
  { id: 'crash-1', date: '2024-09-15', severity: 'minor_injury', lat: 38.5801, lng: -121.4918, pedestrian: true, bicycle: false, location: 'J St & 10th St', primary_factor: 'Failure to yield' },
  { id: 'crash-2', date: '2024-08-22', severity: 'minor_injury', lat: 38.5756, lng: -121.4892, pedestrian: false, bicycle: true, location: 'K St & 15th St', primary_factor: 'Unsafe speed' },
  { id: 'crash-3', date: '2024-07-10', severity: 'serious_injury', lat: 38.5489, lng: -121.4571, pedestrian: true, bicycle: false, location: 'Broadway & MLK Jr Blvd', primary_factor: 'Red light violation' },
  { id: 'crash-4', date: '2024-06-05', severity: 'pdo', lat: 38.5834, lng: -121.4956, pedestrian: false, bicycle: false, location: 'Capitol Mall & 3rd St', primary_factor: 'Following too closely' },
  { id: 'crash-5', date: '2024-05-18', severity: 'minor_injury', lat: 38.5812, lng: -121.4889, pedestrian: false, bicycle: true, location: 'L St & 16th St', primary_factor: 'Improper turning' },
  { id: 'crash-6', date: '2024-04-30', severity: 'fatal', lat: 38.5795, lng: -121.4932, pedestrian: true, bicycle: false, location: 'J St & 7th St', primary_factor: 'Unsafe speed' },
  { id: 'crash-7', date: '2024-03-12', severity: 'minor_injury', lat: 38.5678, lng: -121.4723, pedestrian: false, bicycle: true, location: '21st St & H St', primary_factor: 'Failure to yield' },
  { id: 'crash-8', date: '2024-02-28', severity: 'serious_injury', lat: 38.5901, lng: -121.5012, pedestrian: true, bicycle: false, location: 'Arden Way & Del Paso Blvd', primary_factor: 'Distracted driving' },
  { id: 'crash-9', date: '2024-02-10', severity: 'pdo', lat: 38.5723, lng: -121.4834, pedestrian: false, bicycle: false, location: 'Florin Rd & Stockton Blvd', primary_factor: 'Lane violation' },
  { id: 'crash-10', date: '2024-01-25', severity: 'minor_injury', lat: 38.5645, lng: -121.4912, pedestrian: true, bicycle: false, location: 'Fruitridge Rd & 65th St', primary_factor: 'Failure to yield' },
];

export const DEMO_GRANT_PROGRAMS = [
  {
    id: 'gp-1',
    name: 'Active Transportation Program (ATP)',
    agency: 'Caltrans',
    description: 'Funds projects that encourage walking and bicycling',
    typical_range_min: 500000,
    typical_range_max: 10000000,
    match_required: 11.47,
    url: 'https://catc.ca.gov/programs/active-transportation-program',
  },
  {
    id: 'gp-2',
    name: 'Highway Safety Improvement Program (HSIP)',
    agency: 'Caltrans',
    description: 'Funds infrastructure safety improvements',
    typical_range_min: 100000,
    typical_range_max: 5000000,
    match_required: 10,
    url: 'https://dot.ca.gov/programs/local-assistance/fed-and-state-programs/highway-safety-improvement-program',
  },
  {
    id: 'gp-3',
    name: 'Safe Streets and Roads for All (SS4A)',
    agency: 'USDOT',
    description: 'Supports Vision Zero and safety action plans',
    typical_range_min: 200000,
    typical_range_max: 30000000,
    match_required: 20,
    url: 'https://www.transportation.gov/grants/SS4A',
  },
  {
    id: 'gp-4',
    name: 'RAISE Grants',
    agency: 'USDOT',
    description: 'Rebuilding American Infrastructure with Sustainability and Equity',
    typical_range_min: 5000000,
    typical_range_max: 25000000,
    match_required: 20,
    url: 'https://www.transportation.gov/RAISEgrants',
  },
  {
    id: 'gp-5',
    name: 'Carbon Reduction Program (CRP)',
    agency: 'FHWA',
    description: 'Federal funding for projects that reduce carbon emissions from transportation',
    typical_range_min: 500000,
    typical_range_max: 10000000,
    match_required: 11.47,
    url: 'https://www.fhwa.dot.gov/bipartisan-infrastructure-law/crp.cfm',
  },
  {
    id: 'gp-6',
    name: 'SB 2 Planning Grants',
    agency: 'HCD',
    description: 'Planning grants for local governments to accelerate housing production',
    typical_range_min: 50000,
    typical_range_max: 500000,
    match_required: 0,
    url: 'https://www.hcd.ca.gov/grants-and-funding/programs-active/planning-grants',
  },
  {
    id: 'gp-7',
    name: 'USDA Community Facilities Grant',
    agency: 'USDA',
    description: 'Grants for essential community facilities in rural areas',
    typical_range_min: 10000,
    typical_range_max: 1000000,
    match_required: 25,
    url: 'https://www.rd.usda.gov/programs-services/community-facilities/community-facilities-direct-loan-grant-program',
  },
];

// Caltrans LAPM Demo Data
export const DEMO_CALTRANS_PHASES = [
  {
    id: 'lapm-1',
    project_id: 'proj-1',
    project_name: 'Downtown Complete Streets Plan',
    phase: 'PE',
    e76_number: 'E76-2024-0145',
    e76_date: '2024-03-15',
    authorization_amount: 850000,
    federal_funds: 765000,
    state_funds: 0,
    local_funds: 85000,
    nepa_status: 'approved',
    nepa_approval_date: '2024-06-01',
    pse_certified: false,
    ped_due_date: '2025-03-15',
    dbe_goal: 15,
    dbe_achieved: 12.5,
    status: 'in_progress',
  },
  {
    id: 'lapm-2',
    project_id: 'proj-3',
    project_name: 'Safe Routes to School - Oak Park',
    phase: 'CON',
    e76_number: 'E76-2024-0089',
    e76_date: '2024-01-20',
    authorization_amount: 720000,
    federal_funds: 648000,
    state_funds: 0,
    local_funds: 72000,
    nepa_status: 'exempt',
    pse_certified: true,
    pse_certification_date: '2024-06-15',
    ped_due_date: '2025-01-20',
    dbe_goal: 12,
    dbe_achieved: 14.2,
    status: 'in_progress',
  },
  {
    id: 'lapm-3',
    project_id: 'proj-2',
    project_name: 'American River Trail Extension',
    phase: 'PE',
    e76_number: 'E76-2024-0234',
    e76_date: '2024-09-10',
    authorization_amount: 420000,
    federal_funds: 378000,
    state_funds: 0,
    local_funds: 42000,
    nepa_status: 'in_progress',
    pse_certified: false,
    ped_due_date: '2025-09-10',
    dbe_goal: 15,
    dbe_achieved: 0,
    status: 'authorized',
  },
  {
    id: 'lapm-4',
    project_id: 'proj-4',
    project_name: 'Regional Transit Priority Corridors',
    phase: 'RW',
    e76_number: 'E76-2024-0167',
    e76_date: '2024-04-15',
    authorization_amount: 280000,
    federal_funds: 252000,
    state_funds: 0,
    local_funds: 28000,
    nepa_status: 'approved',
    nepa_approval_date: '2024-07-01',
    pse_certified: false,
    ped_due_date: '2025-04-15',
    dbe_goal: 10,
    dbe_achieved: 8.5,
    status: 'in_progress',
  },
];

export const DEMO_CALTRANS_INVOICES = [
  {
    id: 'inv-1',
    phase_id: 'lapm-1',
    invoice_number: 'INV-2024-001',
    period_start: '2024-03-15',
    period_end: '2024-06-30',
    labor_costs: 125000,
    direct_costs: 45000,
    indirect_costs: 38000,
    total_amount: 208000,
    status: 'paid',
    submitted_at: '2024-07-15T00:00:00Z',
    approved_at: '2024-08-01T00:00:00Z',
    paid_at: '2024-08-15T00:00:00Z',
  },
  {
    id: 'inv-2',
    phase_id: 'lapm-1',
    invoice_number: 'INV-2024-002',
    period_start: '2024-07-01',
    period_end: '2024-09-30',
    labor_costs: 142000,
    direct_costs: 52000,
    indirect_costs: 41000,
    total_amount: 235000,
    status: 'approved',
    submitted_at: '2024-10-10T00:00:00Z',
    approved_at: '2024-11-01T00:00:00Z',
  },
  {
    id: 'inv-3',
    phase_id: 'lapm-2',
    invoice_number: 'INV-2024-003',
    period_start: '2024-06-15',
    period_end: '2024-09-30',
    labor_costs: 185000,
    direct_costs: 98000,
    indirect_costs: 52000,
    total_amount: 335000,
    status: 'under_review',
    submitted_at: '2024-10-20T00:00:00Z',
  },
  {
    id: 'inv-4',
    phase_id: 'lapm-4',
    invoice_number: 'INV-2024-004',
    period_start: '2024-04-15',
    period_end: '2024-07-31',
    labor_costs: 78000,
    direct_costs: 32000,
    indirect_costs: 24000,
    total_amount: 134000,
    status: 'draft',
  },
];

// Environmental Impact Demo Data
export const DEMO_ENVIRONMENTAL_SCENARIOS = [
  {
    id: 'env-1',
    name: 'Downtown TOD Development',
    building: {
      floors: 6,
      totalSqFt: 120000,
      units: 150,
      parkingSpaces: 75,
      buildingType: 'mixed-use' as const,
      affordableHousingPercent: 20,
    },
    scores: {
      walkability: 85,
      bikeability: 72,
      transit: 90,
    },
    tdmPrograms: ['unbundled-parking', 'transit-subsidy', 'bike-parking', 'car-share'],
  },
  {
    id: 'env-2',
    name: 'Suburban Apartment Complex',
    building: {
      floors: 3,
      totalSqFt: 45000,
      units: 48,
      parkingSpaces: 72,
      buildingType: 'residential' as const,
      affordableHousingPercent: 0,
    },
    scores: {
      walkability: 35,
      bikeability: 25,
      transit: 20,
    },
    tdmPrograms: ['ev-charging', 'bike-parking'],
  },
];

// Action Center Demo Data
export const DEMO_MEETINGS = [
  {
    id: 'mtg-1',
    title: 'Downtown Complete Streets Community Workshop',
    meeting_date: '2024-12-05',
    location: 'City Hall, Room 101',
    type: 'community',
  },
  {
    id: 'mtg-2',
    title: 'ATP Cycle 7 Selection Committee',
    meeting_date: '2025-01-08',
    location: 'CTC Office, Sacramento',
    type: 'board',
  },
  {
    id: 'mtg-3',
    title: 'Trail Extension Environmental Review',
    meeting_date: '2024-12-18',
    location: 'Virtual - Zoom',
    type: 'stakeholder',
  },
];

// Helper to check if we're in demo mode
export function isDemoMode(): boolean {
  if (typeof window === 'undefined') return false;
  return localStorage.getItem('planpulse_demo_mode') === 'true';
}

export function enableDemoMode(): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem('planpulse_demo_mode', 'true');
  // Also set a cookie so middleware can read it
  document.cookie = 'planpulse_demo=true; path=/; max-age=86400'; // 24 hours
}

export function disableDemoMode(): void {
  if (typeof window === 'undefined') return;
  localStorage.removeItem('planpulse_demo_mode');
  // Also remove the cookie
  document.cookie = 'planpulse_demo=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT';
}

// Calculate demo stats
export function getDemoStats() {
  return {
    activeProjects: DEMO_PROJECTS.filter(p => p.status === 'active' || p.status === 'planning').length,
    pendingGrants: DEMO_GRANT_APPLICATIONS.filter(g => ['drafting', 'submitted', 'under_review'].includes(g.status)).length,
    totalEngagements: DEMO_ENGAGEMENT_PROJECTS.filter(e => e.status === 'active').length,
    totalInputs: DEMO_COMMUNITY_INPUTS.length,
    caltransPhases: DEMO_CALTRANS_PHASES.filter(p => p.status === 'in_progress' || p.status === 'authorized').length,
    pendingInvoices: DEMO_CALTRANS_INVOICES.filter(i => ['draft', 'submitted', 'under_review'].includes(i.status)).length,
    upcomingMeetings: DEMO_MEETINGS.length,
  };
}

export const DEMO_PROJECT_TASKS = [
  {
    id: 'task-1',
    project_id: 'proj-1',
    title: 'Complete existing conditions analysis',
    description: 'Analyze traffic counts, crash data, and multimodal LOS',
    status: 'done',
    due_date: '2024-04-15',
    assigned_to: 'Demo Planner',
  },
  {
    id: 'task-2',
    project_id: 'proj-1',
    title: 'Draft alternatives analysis',
    description: 'Develop and evaluate 3 design alternatives',
    status: 'in_progress',
    due_date: '2024-12-01',
    assigned_to: 'Demo Planner',
  },
  {
    id: 'task-3',
    project_id: 'proj-1',
    title: 'Public workshop #2',
    description: 'Present alternatives and gather community feedback',
    status: 'todo',
    due_date: '2024-12-15',
    assigned_to: null,
  },
  {
    id: 'task-4',
    project_id: 'proj-2',
    title: 'Environmental review kickoff',
    description: 'Begin CEQA/NEPA documentation process',
    status: 'in_progress',
    due_date: '2024-11-30',
    assigned_to: 'Demo Planner',
  },
  {
    id: 'task-5',
    project_id: 'proj-3',
    title: 'School walk audits',
    description: 'Conduct safety audits at 5 elementary schools',
    status: 'done',
    due_date: '2024-03-01',
    assigned_to: 'Demo Planner',
  },
  {
    id: 'task-6',
    project_id: 'proj-3',
    title: 'Submit PS&E to Caltrans',
    description: 'Prepare and submit Plans, Specifications & Estimates',
    status: 'in_progress',
    due_date: '2024-11-28',
    assigned_to: 'Demo Planner',
  },
];

// Get demo action items for Action Center
export function getDemoActionItems() {
  const { buildActionItems } = require('./data-helpers');
  
  return buildActionItems({
    projects: DEMO_PROJECTS.map(p => ({
      id: p.id,
      name: p.name,
      status: p.status,
      end_date: p.end_date,
    })),
    grants: DEMO_GRANT_APPLICATIONS.map(g => ({
      id: g.id,
      name: g.name,
      deadline: g.deadline,
      status: g.status,
      summary: g.description,
    })),
    caltransPhases: DEMO_CALTRANS_PHASES.map(p => ({
      id: p.id,
      project_id: p.project_id,
      phase: p.phase,
      ped_due_date: p.ped_due_date,
      status: p.status,
    })),
    meetings: DEMO_MEETINGS.map(m => ({
      id: m.id,
      title: m.title,
      meeting_date: m.meeting_date,
      location: m.location,
    })),
    pendingModeration: 5,
  });
}

